### ISSUE TITLE
(전체) 라이트하우스 점수 개선

### ISSUE THREAD

**Issue by sryung1225** [PROJECT-LAB18/POTATO-MARKET#126]

**Comment by tiramin** [comment]
![Image](https://user-images.githubusercontent.com/92783354/227867135-18bc94a9-975f-40d9-9cc7-f47d3ffb8a3d.png)
![Image](https://user-images.githubusercontent.com/92783354/227867554-15c8b7d6-fd85-4ebb-b961-9bff48bf7058.png)
⬇️
![Image](https://user-images.githubusercontent.com/92783354/227867605-700803a7-50b8-41ae-be81-e48884b1d576.png)
![Image](https://user-images.githubusercontent.com/92783354/227867625-e2abb35f-8c16-4765-a3d5-f3678111acc0.png)
