### ISSUE TITLE
(상품상세) 기본 마크업

### ISSUE THREAD

**Issue by DoctorK4** [PROJECT-LAB18/POTATO-MARKET#30]
## ✨ 구현 기능
상품 디테일 마크업, 스타일링 스와이퍼 기능 구현

## ✅ 작업 내용 상세
`npm i swiper`로 설치
![당근마켓 상품디테일 마크업](https://user-images.githubusercontent.com/119388194/224726305-03295514-6169-4985-919a-c8dfbbeebfed.png)
마크업 후 작업
![완성본2](https://user-images.githubusercontent.com/119388194/224726401-e5ad2f4e-0151-494c-86e2-b2113f392b25.png)

## 🙏 비고

아직 router 에 이해가 잘 안돼 `a`태그를 사용했고
styled-component 또한 제대로 알지 못해 css-moduels 마냥 사용했습니다

**Comment by bsw98** [comment]
sda
